# This is a 3.8-compatible configuration, but I could only get docker-compose 
# version 1.25.0 for Ubuntu, at least via "apt install docker-compose". As a 
# result, I had to drop back to 3.7 without needing to make mods.
#
# FWIW, Docker.com advertised a Linux binary that supports a newer Compose 
# specification, it was not supported by Ubuntu. Anyway, no wonder "compose" 
# will be rolled into the docker command itself in an upcoming version.

version: "3.7"

services:
  mongo:
    build:
      context: ../mongo.places
    networks:
      places:
        aliases:
          - placesdb
  node:
    build:
      context: ../express.places
    networks:
      places:
        aliases:
          - placesapp
    depends_on:
      - mongo
  nginx:
    build:
      context: ../nginx.places
    ports:
      - "80:80"
    networks:
      - places
    depends_on:
      - node

networks:
  places:
    driver: bridge
