version: "3.8"

services:
  mongo:
    build:
      context: ../mongo.places
    networks:
      places:
        aliases:
          - placesdb
  node:
    build:
      context: ../express.places
    networks:
      places:
        aliases:
          - placesapp
    depends_on:
      - mongo
  nginx:
    build:
      context: ../nginx.places
    ports:
      - "80:80"
    networks:
      - places
    depends_on:
      - node

networks:
  places:
    driver: bridge